import { useState, useRef } from 'react';
import {
  Upload, FileText, CheckCircle2, AlertTriangle, TrendingUp, BarChart2,
  Check, Activity, ShieldCheck, Pill, FileUp, Sparkles, BrainCircuit,
  Download, FileJson, Sheet
} from 'lucide-react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts';

// ── Updated to working key + model ──
const GEMINI_KEY = 'AIzaSyB1k7J8b9nDJc4ztMY_DWFFyJ4ZZuyalV0';
const GEMINI_MODEL_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_KEY}`;

// ── Analyze clinical report using Gemini 2.5 Flash ──
const analyzeClinicalReport = async (file: File): Promise<{ analysis: string; medications: string[] }> => {
  const isPdf = file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf');
  const isText = file.type.startsWith('text/') || file.name.endsWith('.txt');

  const prompt = `You are a medical AI assistant. Analyze this clinical report and provide:
1. A detailed analysis of the patient's condition, findings, and key observations
2. A list of all medications that may be needed or recommended based on the findings

Format your response EXACTLY as:

ANALYSIS:
[Your detailed analysis here]

SUGGESTED MEDICATIONS:
- Medication 1: [Dosage if mentioned]
- Medication 2: [Dosage if mentioned]

Be thorough and evidence-based. Plain text only.`;

  let bodyParts: any[];

  if (isText) {
    const text = await file.text();
    bodyParts = [{ text: `${prompt}\n\nDocument content:\n${text}` }];
  } else {
    // PDF and images: send as inline base64 data
    const reader = new FileReader();
    const base64Promise = new Promise<string>((resolve, reject) => {
      reader.onload = () => resolve((reader.result as string).split(',')[1]);
      reader.onerror = reject;
    });
    reader.readAsDataURL(file);
    const base64Content = await base64Promise;
    const mimeType = isPdf ? 'application/pdf' : file.type;
    bodyParts = [
      { inlineData: { mimeType, data: base64Content } },
      { text: prompt }
    ];
  }

  const response = await fetch(GEMINI_MODEL_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contents: [{ parts: bodyParts }] })
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err?.error?.message || `API error ${response.status}`);
  }

  const data = await response.json();
  const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

  const medications: string[] = [];
  const lines = responseText.split('\n');
  let inMeds = false;
  for (const line of lines) {
    if (line.includes('SUGGESTED MEDICATIONS') || line.includes('Medications')) { inMeds = true; continue; }
    if (inMeds && (line.trim().startsWith('-') || line.trim().startsWith('•'))) {
      medications.push(line.replace(/^[-•*\s]+/, '').trim());
    }
  }

  return {
    analysis: responseText.split('SUGGESTED MEDICATIONS')[0].replace('ANALYSIS:', '').trim() || responseText,
    medications: medications.length > 0 ? medications : ['No specific medications identified from this report']
  };
};

// ── Export helpers ──
function exportJSON(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename + '.json'; a.click();
  URL.revokeObjectURL(url);
}

function exportCSV(rows: any[], filename: string) {
  if (!rows.length) return;
  const headers = Object.keys(rows[0]).join(',');
  const body = rows.map(r => Object.values(r).map(v => `"${v}"`).join(',')).join('\n');
  const blob = new Blob([headers + '\n' + body], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename + '.csv'; a.click();
  URL.revokeObjectURL(url);
}

function exportPDF(title: string, content: string) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
  <style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:auto;line-height:1.6}
  h1{color:#1e293b;border-bottom:2px solid #3b82f6;padding-bottom:8px}
  pre{background:#f1f5f9;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:13px}
  </style></head><body><h1>${title}</h1><pre>${content}</pre>
  <p style="color:#94a3b8;font-size:11px;margin-top:40px">Generated by Arogya AI · ${new Date().toLocaleString()}</p>
  </body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, '_blank');
  if (w) { setTimeout(() => { w.print(); URL.revokeObjectURL(url); }, 500); }
}

// ── Component ──
export default function DataImporter() {
  const [vitalsFile, setVitalsFile] = useState<File | null>(null);
  const [reportsFile, setReportsFile] = useState<File | null>(null);
  const [clinicalReportFile, setClinicalReportFile] = useState<File | null>(null);
  const [clinicalAnalysis, setClinicalAnalysis] = useState<{ analysis: string; medications: string[] } | null>(null);
  const [clinicalLoading, setClinicalLoading] = useState(false);
  const [clinicalError, setClinicalError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [csvAiInsight, setCsvAiInsight] = useState<string | null>(null);
  const [generatingCsvInsight, setGeneratingCsvInsight] = useState(false);
  const [dragOver, setDragOver] = useState(false);

  const vitalsRef = useRef<HTMLInputElement>(null);
  const reportsRef = useRef<HTMLInputElement>(null);
  const clinicalRef = useRef<HTMLInputElement>(null);

  const generateCsvAiInsight = async (analysisData: any) => {
    setGeneratingCsvInsight(true);
    setCsvAiInsight(null);
    try {
      const prompt = `You are a clinical AI. Analyze this patient vitals ML model training data summary. 
Accuracy: ${(analysisData.metrics.accuracy * 100).toFixed(1)}%, Rows: ${analysisData.metrics.train_size}.
Provide a brief 3-sentence clinical insight on data reliability and patient trend stability.`;

      const response = await fetch(GEMINI_MODEL_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
      });
      const data = await response.json();
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (text) setCsvAiInsight(text);
    } catch { setCsvAiInsight('AI analysis unavailable.'); }
    setGeneratingCsvInsight(false);
  };

  const handleAnalyze = async () => {
    if (!vitalsFile) { setError('Please upload at least a Vitals CSV file.'); return; }
    setLoading(true); setError(null); setResults(null); setCsvAiInsight(null);
    try {
      const formData = new FormData();
      formData.append('vitals', vitalsFile);
      if (reportsFile) formData.append('reports', reportsFile);
      const res = await fetch('http://localhost:5000/api/analyze-csvs', { method: 'POST', body: formData });
      const data = await res.json();
      if (res.ok) { setResults(data); generateCsvAiInsight(data); }
      else setError(data.error || 'Failed to analyze data.');
    } catch (e: any) { setError(e.message || 'Network error.'); }
    setLoading(false);
  };

  const handleClinicalFile = async (file: File) => {
    const allowed = ['application/pdf', 'text/plain', 'image/jpeg', 'image/png', 'image/jpg'];
    const allowedExts = ['.pdf', '.txt', '.jpg', '.jpeg', '.png'];
    const ext = '.' + file.name.split('.').pop()?.toLowerCase();
    if (!allowed.includes(file.type) && !allowedExts.includes(ext)) {
      setClinicalError(`File type not supported. Please upload PDF, TXT, JPG, or PNG.`);
      return;
    }
    if (file.size > 20 * 1024 * 1024) {
      setClinicalError('File too large. Maximum size is 20MB.'); return;
    }
    setClinicalReportFile(file);
    setClinicalLoading(true);
    setClinicalAnalysis(null);
    setClinicalError(null);
    try {
      const result = await analyzeClinicalReport(file);
      setClinicalAnalysis(result);
    } catch (e: any) {
      setClinicalError('Failed to analyze report: ' + (e.message || 'Unknown error'));
    }
    setClinicalLoading(false);
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-12">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-black text-white tracking-tight flex items-center gap-3">
          <Upload className="w-8 h-8 text-cyan-400" /> Arogya AI Analysis
        </h1>
        <p className="text-white/50 mt-1">Upload clinical reports for AI analysis, or batch-analyze CSV vitals data with ML models.</p>
      </div>

      {/* ━━ Clinical Report Upload ━━ */}
      <div className="rounded-2xl bg-[#0d1525] border border-white/[0.08] p-8 space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-purple-500/20 rounded-xl">
              <Sparkles className="w-5 h-5 text-purple-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Clinical Report Intelligence</h2>
              <p className="text-sm text-white/40 mt-0.5">Upload a PDF, image, or text file — Gemini AI extracts insights & medications</p>
            </div>
          </div>
          <span className="text-[10px] font-black text-purple-400 bg-purple-500/10 border border-purple-500/20 px-3 py-1.5 rounded-full uppercase tracking-widest">
            Gemini 2.5 Flash
          </span>
        </div>

        {/* Drop Zone */}
        <div
          className={`rounded-xl border-2 border-dashed transition-all duration-300 p-10 text-center cursor-pointer ${
            dragOver
              ? 'border-purple-400 bg-purple-500/15 scale-[1.01]'
              : 'border-purple-500/30 bg-purple-500/5 hover:bg-purple-500/10 hover:border-purple-400/50'
          }`}
          onClick={() => clinicalRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={(e) => {
            e.preventDefault(); setDragOver(false);
            const file = e.dataTransfer.files[0];
            if (file) handleClinicalFile(file);
          }}
        >
          <input
            type="file"
            ref={clinicalRef}
            className="hidden"
            accept=".pdf,.txt,.jpg,.jpeg,.png"
            onChange={(e) => { const f = e.target.files?.[0]; if (f) handleClinicalFile(f); e.target.value = ''; }}
          />
          <div className="flex flex-col items-center gap-3">
            <div className={`p-4 bg-purple-500/15 rounded-full transition-transform ${dragOver ? 'scale-110' : ''}`}>
              <FileUp className="w-8 h-8 text-purple-400" />
            </div>
            {clinicalReportFile ? (
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                <span className="text-white/80 font-semibold text-sm">{clinicalReportFile.name}</span>
              </div>
            ) : (
              <>
                <p className="text-white/80 font-semibold text-lg">Drop your clinical report here</p>
                <p className="text-sm text-white/40">or click to browse</p>
              </>
            )}
            {/* Accepted formats */}
            <div className="flex flex-wrap justify-center gap-2 mt-2">
              {[['PDF', '#a855f7'], ['TXT', '#06b6d4'], ['JPG', '#f59e0b'], ['PNG', '#10b981']].map(([fmt, color]) => (
                <span key={fmt} className="text-[10px] font-bold px-2.5 py-1 rounded-full border"
                  style={{ color, borderColor: color + '40', backgroundColor: color + '15' }}>
                  .{fmt}
                </span>
              ))}
              <span className="text-[10px] text-white/30 self-center">· up to 20MB</span>
            </div>
          </div>
        </div>

        {/* Loading */}
        {clinicalLoading && (
          <div className="flex items-center gap-3 bg-purple-500/10 border border-purple-500/20 rounded-xl p-5">
            <div className="w-5 h-5 border-2 border-purple-400/30 border-t-purple-400 rounded-full animate-spin flex-shrink-0" />
            <span className="text-purple-300 font-semibold">Analyzing report with Gemini AI...</span>
          </div>
        )}

        {/* Error */}
        {clinicalError && (
          <div className="flex items-start gap-3 bg-red-500/5 border border-red-500/20 rounded-xl p-4">
            <AlertTriangle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-red-300 font-semibold text-sm">Analysis Failed</p>
              <p className="text-red-200/60 text-xs mt-1">{clinicalError}</p>
            </div>
            <button
              onClick={() => { setClinicalError(null); if (clinicalReportFile) handleClinicalFile(clinicalReportFile); }}
              className="text-xs text-red-400 font-bold hover:text-white transition-colors px-3 py-1.5 bg-red-500/10 rounded-lg border border-red-500/20"
            >Retry</button>
          </div>
        )}

        {/* AI Analysis Results */}
        {clinicalAnalysis && (
          <div className="space-y-5 animate-in slide-in-from-bottom-4 duration-500">
            {/* Export buttons */}
            <div className="flex flex-wrap gap-2 justify-end">
              <button
                onClick={() => exportPDF('Clinical Report Analysis', clinicalAnalysis.analysis + '\n\nMEDICATIONS:\n' + clinicalAnalysis.medications.join('\n'))}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-red-300 bg-red-500/10 border border-red-500/20 rounded-lg hover:bg-red-500/20 transition-all"
              ><Download className="w-3 h-3" /> Export PDF</button>
              <button
                onClick={() => exportJSON({ analysis: clinicalAnalysis.analysis, medications: clinicalAnalysis.medications, file: clinicalReportFile?.name, timestamp: new Date().toISOString() }, 'clinical-analysis')}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-amber-300 bg-amber-500/10 border border-amber-500/20 rounded-lg hover:bg-amber-500/20 transition-all"
              ><FileJson className="w-3 h-3" /> Export JSON</button>
              <button
                onClick={() => exportCSV([{ analysis: clinicalAnalysis.analysis.replace(/\n/g, ' '), medications: clinicalAnalysis.medications.join('; '), file: clinicalReportFile?.name }], 'clinical-analysis')}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-emerald-300 bg-emerald-500/10 border border-emerald-500/20 rounded-lg hover:bg-emerald-500/20 transition-all"
              ><Sheet className="w-3 h-3" /> Export CSV</button>
            </div>

            {/* Analysis Block */}
            <div className="rounded-xl bg-black/30 border border-purple-500/20 p-6 relative overflow-hidden">
              <div className="absolute top-3 right-3 opacity-5 pointer-events-none"><BrainCircuit className="w-20 h-20 text-purple-300" /></div>
              <h3 className="text-sm font-black text-purple-400 uppercase tracking-widest mb-3 flex items-center gap-2 relative z-10">
                <FileText className="w-4 h-4" /> AI Assessment
              </h3>
              <div className="text-white/75 text-sm leading-relaxed whitespace-pre-wrap max-h-72 overflow-y-auto pr-2 relative z-10">
                {clinicalAnalysis.analysis}
              </div>
            </div>

            {/* Medications Block */}
            <div className="rounded-xl bg-pink-500/5 border border-pink-500/20 p-6">
              <h3 className="text-sm font-black text-pink-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                <Pill className="w-4 h-4" /> Suggested Medications ({clinicalAnalysis.medications.length})
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
                {clinicalAnalysis.medications.map((med, i) => (
                  <div key={i} className="flex items-start gap-2 bg-white/[0.03] border border-white/[0.05] rounded-lg px-3 py-2.5">
                    <Pill className="w-3.5 h-3.5 text-pink-400 flex-shrink-0 mt-0.5" />
                    <span className="text-white/75 text-[13px] leading-relaxed">{med}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ━━ Batch CSV Analysis ━━ */}
      <div className="rounded-2xl bg-[#0d1525] border border-white/[0.08] p-8 space-y-6">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-cyan-500/20 rounded-xl"><Activity className="w-5 h-5 text-cyan-400" /></div>
          <div>
            <h2 className="text-xl font-bold text-white">Batch Predictive Analysis</h2>
            <p className="text-sm text-white/40 mt-0.5">Train and validate ML models on custom CSV datasets</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Vitals CSV */}
          <div
            className="rounded-xl border border-white/[0.08] bg-black/20 p-6 flex flex-col items-center text-center cursor-pointer hover:border-cyan-500/30 hover:bg-black/30 transition-all group"
            onClick={() => vitalsRef.current?.click()}
          >
            <input type="file" ref={vitalsRef} className="hidden" accept=".csv"
              onChange={e => setVitalsFile(e.target.files?.[0] || null)} />
            <div className="p-4 bg-cyan-500/10 rounded-full mb-3 group-hover:bg-cyan-500/20 transition-all">
              <Activity className="w-7 h-7 text-cyan-400" />
            </div>
            <h3 className="font-bold text-white mb-1">Vitals CSV <span className="text-red-400 text-xs">*Required</span></h3>
            <p className="text-xs text-white/40">{vitalsFile ? vitalsFile.name : 'Click or drag CSV file here'}</p>
            {vitalsFile && <CheckCircle2 className="w-5 h-5 text-emerald-400 mt-3" />}
          </div>

          {/* Reports CSV */}
          <div
            className="rounded-xl border border-white/[0.08] bg-black/20 p-6 flex flex-col items-center text-center cursor-pointer hover:border-fuchsia-500/30 hover:bg-black/30 transition-all group"
            onClick={() => reportsRef.current?.click()}
          >
            <input type="file" ref={reportsRef} className="hidden" accept=".csv"
              onChange={e => setReportsFile(e.target.files?.[0] || null)} />
            <div className="p-4 bg-fuchsia-500/10 rounded-full mb-3 group-hover:bg-fuchsia-500/20 transition-all">
              <FileText className="w-7 h-7 text-fuchsia-400" />
            </div>
            <h3 className="font-bold text-white mb-1">Reports CSV <span className="text-white/30 text-xs">Optional</span></h3>
            <p className="text-xs text-white/40">{reportsFile ? reportsFile.name : 'Click or drag CSV file here'}</p>
            {reportsFile && <CheckCircle2 className="w-5 h-5 text-emerald-400 mt-3" />}
          </div>
        </div>

        <button
          onClick={handleAnalyze}
          disabled={loading || !vitalsFile}
          className="w-full py-4 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white font-bold flex items-center justify-center gap-3 transition-all shadow-lg hover:shadow-cyan-500/20 disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {loading ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <Activity className="w-5 h-5" />}
          <span className="text-base">{loading ? 'Training & Analyzing...' : 'Run ML Analysis'}</span>
        </button>

        {error && (
          <div className="flex items-start gap-3 bg-red-500/5 border border-red-500/20 rounded-xl p-4">
            <AlertTriangle className="w-5 h-5 text-red-400 flex-shrink-0" />
            <span className="text-red-300 text-sm font-medium">{error}</span>
          </div>
        )}
      </div>

      {/* ━━ Results ━━ */}
      {results && (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
          {/* Export buttons */}
          <div className="flex flex-wrap gap-2 justify-end">
            <button
              onClick={() => exportPDF('ML Analysis Report', `Accuracy: ${(results.metrics.accuracy * 100).toFixed(1)}%\nRows: ${results.metrics.train_size}\nPrediction: ${results.latest_prediction}\n\nAI Insight:\n${csvAiInsight || 'N/A'}`)}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-red-300 bg-red-500/10 border border-red-500/20 rounded-lg hover:bg-red-500/20 transition-all"
            ><Download className="w-3 h-3" /> Export PDF</button>
            <button
              onClick={() => exportJSON(results, 'ml-analysis-results')}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-amber-300 bg-amber-500/10 border border-amber-500/20 rounded-lg hover:bg-amber-500/20 transition-all"
            ><FileJson className="w-3 h-3" /> Export JSON</button>
            {results.comparisons?.length > 0 && (
              <button
                onClick={() => exportCSV(results.comparisons, 'report-comparisons')}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-emerald-300 bg-emerald-500/10 border border-emerald-500/20 rounded-lg hover:bg-emerald-500/20 transition-all"
              ><Sheet className="w-3 h-3" /> Export Comparisons CSV</button>
            )}
          </div>

          {/* Gemini AI Insight */}
          <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-6">
            <h3 className="text-sm font-black text-cyan-400 uppercase tracking-widest mb-3 flex items-center gap-2">
              <Sparkles className="w-4 h-4" /> Gemini AI Insight
            </h3>
            {generatingCsvInsight ? (
              <div className="flex items-center gap-2 text-white/50">
                <div className="w-4 h-4 border-2 border-cyan-400/30 border-t-cyan-400 rounded-full animate-spin" />
                <span className="text-sm">Generating clinical insight...</span>
              </div>
            ) : csvAiInsight ? (
              <p className="text-white/75 text-sm leading-relaxed">{csvAiInsight}</p>
            ) : null}
          </div>

          {/* Metrics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: 'Model Accuracy', value: (results.metrics.accuracy * 100).toFixed(1) + '%', color: 'text-cyan-400' },
              { label: 'Agreement w/ Reports', value: results.agreement ? results.agreement.toFixed(1) + '%' : 'N/A', color: 'text-fuchsia-400' },
              { label: 'Rows Trained', value: results.metrics.train_size, color: 'text-white/90' },
              { label: 'Latest Prediction', value: results.latest_prediction, color: 'text-amber-400' },
            ].map(({ label, value, color }) => (
              <div key={label} className="rounded-xl bg-white/[0.03] border border-white/[0.07] p-5">
                <p className="text-xs text-white/40 mb-1">{label}</p>
                <p className={`text-2xl font-black truncate ${color}`}>{value}</p>
              </div>
            ))}
          </div>

          {/* Charts */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div className="rounded-xl bg-white/[0.03] border border-white/[0.07] p-6">
              <h3 className="text-sm font-bold text-white/70 mb-4 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-cyan-400" /> Vital Trends
              </h3>
              <div className="h-56">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={results.trend_data}>
                    <XAxis dataKey="timestamp" hide />
                    <YAxis stroke="#ffffff30" fontSize={10} width={30} />
                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: 8 }} />
                    <Legend />
                    <Line type="monotone" dataKey="heart_rate" stroke="#ef4444" strokeWidth={2} dot={false} />
                    <Line type="monotone" dataKey="spo2" stroke="#3b82f6" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="rounded-xl bg-white/[0.03] border border-white/[0.07] p-6">
              <h3 className="text-sm font-bold text-white/70 mb-4 flex items-center gap-2">
                <BarChart2 className="w-4 h-4 text-fuchsia-400" /> Condition Distribution
              </h3>
              <div className="h-56">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={results.dist_data}>
                    <XAxis dataKey="condition" stroke="#ffffff30" fontSize={11} />
                    <YAxis stroke="#ffffff30" fontSize={10} width={30} hide />
                    <Tooltip cursor={{ fill: 'rgba(255,255,255,0.03)' }} contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: 8 }} />
                    <Bar dataKey="count" fill="#8b5cf6" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* Comparison Table */}
          {results.comparisons?.length > 0 && (
            <div className="rounded-xl bg-white/[0.03] border border-white/[0.07] p-6">
              <h3 className="text-sm font-bold text-white/70 mb-4 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-400" /> Report Cross-Validation
              </h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm text-left text-white/70">
                  <thead className="text-[11px] text-white/40 uppercase">
                    <tr className="border-b border-white/[0.06]">
                      <th className="px-4 py-3">Patient ID</th>
                      <th className="px-4 py-3">Timestamp</th>
                      <th className="px-4 py-3">Predicted</th>
                      <th className="px-4 py-3">Reported</th>
                      <th className="px-4 py-3">Match</th>
                    </tr>
                  </thead>
                  <tbody>
                    {results.comparisons.map((row: any, i: number) => (
                      <tr key={i} className="border-b border-white/[0.04] hover:bg-white/[0.02] transition-colors">
                        <td className="px-4 py-3 text-white/90 font-medium">{row.patient_id}</td>
                        <td className="px-4 py-3">{String(row.timestamp).split(' ')[0]}</td>
                        <td className="px-4 py-3">{row.predicted_condition}</td>
                        <td className="px-4 py-3">{row.reported_condition}</td>
                        <td className="px-4 py-3">
                          {row.match
                            ? <Check className="w-4 h-4 text-emerald-400" />
                            : <AlertTriangle className="w-4 h-4 text-amber-400" />}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
