import { useState, useRef, useEffect } from 'react';
import {
  FileText, CheckCircle2, AlertTriangle, ArrowRight,
  Activity, Wind, FileUp, Sparkles, Pill, BrainCircuit,
  Download, FileJson, X
} from 'lucide-react';
import GlassCard from '../components/GlassCard';
import { useRole } from '../hooks/RoleContext';

const GEMINI_KEY = 'AIzaSyB1k7J8b9nDJc4ztMY_DWFFyJ4ZZuyalV0';

// ── Export helpers ──
function exportJSON(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename + '.json'; a.click();
  URL.revokeObjectURL(url);
}

function exportPDF(title: string, content: string) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
  <style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:auto;line-height:1.6;color:#1e293b}
  h1{border-bottom:2px solid #3b82f6;padding-bottom:8px}
  pre{background:#f1f5f9;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:13px}
  </style></head><body><h1>${title}</h1><pre>${content}</pre>
  <p style="color:#94a3b8;font-size:11px;margin-top:40px">Generated by Arogya AI · ${new Date().toLocaleString()}</p>
  </body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, '_blank');
  if (w) setTimeout(() => { w.print(); URL.revokeObjectURL(url); }, 500);
}

// ── Gemini analysis ──
async function analyzeReportWithGemini(file: File): Promise<{ analysis: string; conditions: string[]; medications: string[]; risks: string[] }> {
  const isText = file.type.startsWith('text/') || file.name.endsWith('.txt');

  const prompt = `You are a clinical AI assistant. Analyze this uploaded medical/clinical report carefully.

Extract and provide the following in PLAIN TEXT (no markdown):

ANALYSIS:
A 4-6 sentence summary of the patient's clinical status, key findings, and important observations.

CONDITIONS:
List each diagnosis/condition on its own line starting with "-"

MEDICATIONS:
List each medication with dosage on its own line starting with "-"

RISKS:
List each clinical risk or warning on its own line starting with "-"

Be thorough, evidence-based, and professional.`;

  let parts: any[];
  if (isText) {
    const text = await file.text();
    parts = [{ text: `${prompt}\n\nDocument:\n${text}` }];
  } else {
    const reader = new FileReader();
    const b64 = await new Promise<string>((res, rej) => {
      reader.onload = () => res((reader.result as string).split(',')[1]);
      reader.onerror = rej;
      reader.readAsDataURL(file);
    });
    const mime = file.type === 'application/pdf' || file.name.endsWith('.pdf') ? 'application/pdf' : file.type;
    parts = [{ inlineData: { mimeType: mime, data: b64 } }, { text: prompt }];
  }

  const resp = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts }] })
    }
  );

  if (!resp.ok) {
    const err = await resp.json().catch(() => ({}));
    throw new Error(err?.error?.message || `API error ${resp.status}`);
  }

  const data = await resp.json();
  const text: string = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

  const extractList = (marker: string): string[] => {
    const idx = text.indexOf(marker);
    if (idx === -1) return [];
    const nextMarker = ['CONDITIONS:', 'MEDICATIONS:', 'RISKS:', 'ANALYSIS:']
      .filter(m => m !== marker)
      .map(m => text.indexOf(m, idx + marker.length))
      .filter(i => i > -1);
    const end = nextMarker.length ? Math.min(...nextMarker) : text.length;
    return text.slice(idx + marker.length, end)
      .split('\n')
      .map(l => l.replace(/^[-•*\s]+/, '').trim())
      .filter(Boolean);
  };

  const analysisMatch = text.match(/ANALYSIS:\s*([\s\S]*?)(?=CONDITIONS:|MEDICATIONS:|RISKS:|$)/);
  return {
    analysis: analysisMatch?.[1]?.trim() || text.slice(0, 500),
    conditions: extractList('CONDITIONS:'),
    medications: extractList('MEDICATIONS:'),
    risks: extractList('RISKS:'),
  };
}

export default function MedicalReports() {
  const { role } = useRole();
  const fileRef = useRef<HTMLInputElement>(null);

  const [file, setFile] = useState<File | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{ analysis: string; conditions: string[]; medications: string[]; risks: string[] } | null>(null);
  const [showStaticView, setShowStaticView] = useState(false);

  // Block browser default drag-to-open-file behavior on the entire page
  useEffect(() => {
    const prevent = (e: DragEvent) => { e.preventDefault(); e.stopPropagation(); };
    document.addEventListener('dragover', prevent);
    document.addEventListener('drop', prevent);
    return () => {
      document.removeEventListener('dragover', prevent);
      document.removeEventListener('drop', prevent);
    };
  }, []);

  const handleFile = async (f: File) => {
    const allowed = ['application/pdf', 'text/plain', 'image/jpeg', 'image/png', 'image/jpg'];
    const allowedExts = ['.pdf', '.txt', '.jpg', '.jpeg', '.png', '.doc', '.docx'];
    const ext = '.' + f.name.split('.').pop()?.toLowerCase();
    if (!allowed.includes(f.type) && !allowedExts.includes(ext)) {
      setError(`Unsupported file type. Please upload PDF, TXT, JPG, or PNG.`);
      return;
    }
    if (f.size > 20 * 1024 * 1024) { setError('File too large. Max size is 20MB.'); return; }

    setFile(f);
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await analyzeReportWithGemini(f);
      setResult(res);
      setShowStaticView(false);
    } catch (e: any) {
      setError(e.message || 'Failed to analyze report. Please try again.');
    }
    setLoading(false);
  };

  const reset = () => { setFile(null); setResult(null); setError(null); setShowStaticView(false); };

  if (role !== 'physician') {
    return (
      <div style={{ maxWidth: 800, margin: '100px auto', textAlign: 'center' }}>
        <GlassCard>
          <FileText size={48} style={{ color: 'var(--accent-cyan)', margin: '0 auto 24px auto' }} />
          <h2 style={{ fontSize: 24, marginBottom: 16 }}>Clinical History Intact</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: 16, lineHeight: 1.6 }}>
            Your full medical history, lab results, and previous physician notes have been securely
            integrated into your AI monitoring profile to provide perfectly personalized care.
          </p>
        </GlassCard>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-12">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-black text-white tracking-tight">Medical Report Integration</h1>
        <p className="text-white/50 mt-1">Upload clinical PDFs, images, or text files — Gemini AI extracts conditions, medications & risk factors.</p>
      </div>

      {/* Upload Zone */}
      <div className="rounded-2xl bg-[#0d1525] border border-white/[0.08] p-6">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-purple-500/20 rounded-xl"><BrainCircuit className="w-5 h-5 text-purple-400" /></div>
            <div>
              <h2 className="font-bold text-white">Upload Patient Record</h2>
              <p className="text-xs text-white/40 mt-0.5">Supports PDF, TXT, JPG, PNG · up to 20MB</p>
            </div>
          </div>
          <span className="text-[10px] font-black text-purple-300 bg-purple-500/10 border border-purple-500/20 px-2.5 py-1.5 rounded-full uppercase tracking-widest">
            Gemini 2.5 Flash
          </span>
        </div>

        {/* Drop zone */}
        <div
          className={`rounded-xl border-2 border-dashed transition-all duration-300 p-10 text-center cursor-pointer select-none ${
            dragOver
              ? 'border-purple-400 bg-purple-500/15 scale-[1.01]'
              : file && !error
              ? 'border-emerald-400/50 bg-emerald-500/5'
              : 'border-purple-500/30 bg-purple-500/5 hover:border-purple-400/50 hover:bg-purple-500/10'
          }`}
          onClick={() => { if (!loading) fileRef.current?.click(); }}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={(e) => {
            e.preventDefault(); setDragOver(false);
            const f = e.dataTransfer.files[0];
            if (f) handleFile(f);
          }}
        >
          <input
            type="file"
            ref={fileRef}
            className="hidden"
            accept=".pdf,.txt,.jpg,.jpeg,.png,.doc,.docx"
            onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); e.target.value = ''; }}
          />

          {loading ? (
            <div className="flex flex-col items-center gap-4">
              <div className="w-12 h-12 border-3 border-purple-400/30 border-t-purple-400 rounded-full animate-spin" style={{ borderWidth: 3 }} />
              <p className="text-purple-300 font-semibold">Analyzing with Gemini AI...</p>
              <p className="text-white/30 text-sm">Extracting conditions, medications & risks</p>
            </div>
          ) : file && result ? (
            <div className="flex flex-col items-center gap-2">
              <CheckCircle2 className="w-12 h-12 text-emerald-400" />
              <p className="text-emerald-400 font-bold text-lg">{file.name}</p>
              <p className="text-white/40 text-sm">Analysis complete · click to upload a different file</p>
            </div>
          ) : (
            <div className="flex flex-col items-center gap-3">
              <div className={`p-4 rounded-full bg-purple-500/15 transition-transform ${dragOver ? 'scale-110' : ''}`}>
                <FileUp className="w-8 h-8 text-purple-400" />
              </div>
              <p className="text-white/80 font-semibold text-lg">Drag &amp; drop clinical report here</p>
              <p className="text-white/40 text-sm">or click to browse</p>
              <div className="flex gap-2 mt-1">
                {[['PDF', '#a855f7'], ['TXT', '#06b6d4'], ['JPG', '#f59e0b'], ['PNG', '#10b981']].map(([f, c]) => (
                  <span key={f} className="text-[10px] font-bold px-2.5 py-1 rounded-full border"
                    style={{ color: c, borderColor: c + '40', backgroundColor: c + '15' }}>.{f}</span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="mt-4 flex items-start gap-3 bg-red-500/5 border border-red-500/20 rounded-xl p-4">
            <AlertTriangle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-red-300 font-semibold text-sm">Upload Failed</p>
              <p className="text-red-200/50 text-xs mt-1">{error}</p>
            </div>
            <button onClick={reset} className="text-red-400 hover:text-white transition-colors"><X className="w-4 h-4" /></button>
          </div>
        )}
      </div>

      {/* AI Analysis Results */}
      {result && (
        <div className="space-y-5 animate-in slide-in-from-bottom-4 duration-500">
          {/* Export bar */}
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold text-white/50 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-400" /> AI Analysis Results
            </p>
            <div className="flex gap-2">
              <button
                onClick={() => exportPDF('Clinical Report Analysis — ' + file?.name, result.analysis + '\n\nCONDITIONS:\n' + result.conditions.join('\n') + '\n\nMEDICATIONS:\n' + result.medications.join('\n') + '\n\nRISKS:\n' + result.risks.join('\n'))}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-red-300 bg-red-500/10 border border-red-500/20 rounded-lg hover:bg-red-500/20 transition-all"
              ><Download className="w-3 h-3" /> PDF</button>
              <button
                onClick={() => exportJSON({ file: file?.name, timestamp: new Date().toISOString(), ...result }, 'report-analysis')}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-amber-300 bg-amber-500/10 border border-amber-500/20 rounded-lg hover:bg-amber-500/20 transition-all"
              ><FileJson className="w-3 h-3" /> JSON</button>
              <button onClick={reset} className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold text-white/40 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-all">
                <X className="w-3 h-3" /> Clear
              </button>
            </div>
          </div>

          {/* Analysis */}
          <div className="rounded-xl bg-[#0d1525] border border-purple-500/20 p-6">
            <h3 className="text-xs font-black text-purple-400 uppercase tracking-widest mb-3 flex items-center gap-2">
              <BrainCircuit className="w-4 h-4" /> AI Assessment
            </h3>
            <p className="text-white/75 text-sm leading-relaxed">{result.analysis}</p>
          </div>

          {/* 3-column data */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Conditions */}
            <div className="rounded-xl bg-[#0d1525] border border-cyan-500/20 p-5">
              <h3 className="text-xs font-black text-cyan-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                <Activity className="w-3.5 h-3.5" /> Conditions ({result.conditions.length})
              </h3>
              {result.conditions.length ? (
                <div className="flex flex-wrap gap-2">
                  {result.conditions.map((c, i) => (
                    <span key={i} className="text-xs px-2.5 py-1 bg-cyan-500/10 text-cyan-300 border border-cyan-500/20 rounded-full">{c}</span>
                  ))}
                </div>
              ) : <p className="text-white/30 text-xs">No conditions identified</p>}
            </div>

            {/* Medications */}
            <div className="rounded-xl bg-[#0d1525] border border-purple-500/20 p-5">
              <h3 className="text-xs font-black text-purple-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                <Pill className="w-3.5 h-3.5" /> Medications ({result.medications.length})
              </h3>
              {result.medications.length ? (
                <div className="space-y-1.5">
                  {result.medications.map((m, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-white/70">
                      <Pill className="w-3 h-3 text-purple-400 flex-shrink-0 mt-0.5" />{m}
                    </div>
                  ))}
                </div>
              ) : <p className="text-white/30 text-xs">No medications identified</p>}
            </div>

            {/* Risks */}
            <div className="rounded-xl bg-[#0d1525] border border-red-500/20 p-5">
              <h3 className="text-xs font-black text-red-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                <AlertTriangle className="w-3.5 h-3.5" /> Risk Factors ({result.risks.length})
              </h3>
              {result.risks.length ? (
                <div className="space-y-1.5">
                  {result.risks.map((r, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-white/70">
                      <AlertTriangle className="w-3 h-3 text-red-400 flex-shrink-0 mt-0.5" />{r}
                    </div>
                  ))}
                </div>
              ) : <p className="text-white/30 text-xs">No specific risks identified</p>}
            </div>
          </div>
        </div>
      )}

      {/* Static baseline adjustments — only shown if nothing uploaded or after AI analysis */}
      {(result || showStaticView) && (
        <div className="rounded-2xl bg-[#0d1525] border border-white/[0.08] p-6">
          <div className="flex items-center justify-between mb-5">
            <h3 className="font-bold text-white flex items-center gap-2">
              <Activity className="w-4 h-4 text-emerald-400" /> AI Baseline Auto-Adjustments
            </h3>
            <span className="text-xs text-white/30">Based on patient history from {file?.name ?? 'Medical Record'}</span>
          </div>
          <div className="rounded-xl border border-white/[0.07] overflow-hidden">
            <div className="grid grid-cols-3 bg-black/30 px-4 py-3 text-[11px] font-bold text-white/30 uppercase tracking-widest">
              <div>Trigger Entity</div><div>Baseline Adjustment</div><div>Clinical Reasoning</div>
            </div>
            {[
              { icon: <Activity className="w-4 h-4" />, color: 'text-emerald-400', label: 'Hypertension', from: '120/80', to: '135-145 SBP', reason: 'Accepting higher normotensive range to prevent false alarms for stage 2 HTN.' },
              { icon: <Wind className="w-4 h-4" />, color: 'text-purple-400', label: 'Asthma', from: 'SpO2 Alert: <95%', to: 'Alert: <93% OR -3%/hr', reason: 'Sensitive to trajectory velocity rather than absolute threshold due to mild persistence.' },
              { icon: <AlertTriangle className="w-4 h-4" />, color: 'text-red-400', label: 'Beta-Blocker', from: 'Max HR: 180', to: 'Max HR: 120 ⚠️', reason: 'Conflict Rule: If HR > 100, alert for sympathetic override or poor medication adherence.', highlight: true },
            ].map((row, i) => (
              <div key={i} className={`grid grid-cols-3 px-4 py-4 border-t border-white/[0.05] items-center gap-4 text-sm ${row.highlight ? 'bg-red-500/[0.04]' : ''}`}>
                <div className={`flex items-center gap-2 font-medium ${row.color}`}>{row.icon}{row.label}</div>
                <div className="flex items-center gap-2 text-white/70">
                  <span className="line-through text-white/30 text-xs">{row.from}</span>
                  <ArrowRight className="w-3 h-3 text-white/20 flex-shrink-0" />
                  <span className="font-semibold text-white/90">{row.to}</span>
                </div>
                <div className="text-xs text-white/50 leading-relaxed">{row.reason}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Show static view button if nothing uploaded yet */}
      {!result && !loading && (
        <div className="text-center">
          <button
            onClick={() => { setShowStaticView(true); setResult(null); }}
            className="text-xs text-white/30 hover:text-white/60 transition-colors underline underline-offset-2"
          >
            Preview with sample patient data →
          </button>
        </div>
      )}

      <style>{`@keyframes spin { 100% { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
